name: Terraform Deploy prod

on:
  push:
    branches:
      - prod

jobs:
  terraform:
    uses: ./.github/actions/terraform-apply-action  # referring to the reusable action.yaml
    with:
      tf_dir: "environments/prod"                    # point to your prod env terraform directory
      tfvar_file: "environments/prod.tfvars"         # your prod-specific variables file
      environment: "prod"
      workspace: "prod"
      workload_identity_provider: ""                 # Leave blank for now
      gauth_sa: ""                                   # Leave blank, to fill upon impersonation details
      lock-timeout: "10s"                            # can adjust the locking timeout if needed
